### PR TITLE
Add tool for generating the url to the job argument steps

### PR DESCRIPTION
**Pull request by tthyer**
This works but is very dependent that the right tools be installed in the environment and I'm unhappy with the complexity of this solution. Using a docker image did not help because there were multiple problems using git with the CWL Directory type. Actually, there's another way of doing this with Docker that would work but still require some changes in the tool. And it's just too complex.

Alternatives:
1. add args file to itself as a file, save that file to Synapse, get the synapse ID and version number, supply those as inputs to the provenance tool
2. use all strings that the user has to add and simplify the tool into merely formatting those together correctly -- but that could be done in the provenance tool itself
3. keep the script as a utility that the user can run to generate the input for provenance  (I have a simplified version of the bash script saved elsewhere)

I like #1 the best. @wpoehlm, what do you think?

If we decide to keep this tool in its current state, I will remove the test.yaml and add several unit tests based on it instead.

### CODE REVIEW

**Review by wpoehlm — CHANGES_REQUESTED** [review]
Ok so first impression is that I don't mind the complexity of the code as I had no problem getting it to run.  However, I do wonder if this is a good strategy in general, as I feel like the work required by the user (and potential for human error) with this approach is just as bad as requiring the user to supply the url itself as input into the workflow.  Also, when I ran it, the resulting link was not valid (could be something I did wrong).  

Using the following test yaml input:

job_args_path: jobs/test-main-paired/job.json
git_dir: /home/wpoehlm/Testing/Test_PR/.git

the resulting url was: https://github.com/Sage-Bionetworks/amp-workf/blob/734ac5b99c64c962494a857b2e93d8ebc61fd8e4amp-rnaseq_reprocessing/amp-rnaseq_reprocess-workflow/jobs/test-main-paired/job.json

which is not a valid URL even after fixing the missing forward slash

**Comment by tthyer** [comment]
@wpoehlm Sadly, when I rerun the tool with the arguments in test.yaml, I get this perfectly usable url: https://github.com/Sage-Bionetworks/amp-workflows/blob/89c4448d281b280c8a081810a91b5f803be69cf2/amp-rnaseq_reprocessing/amp-rnaseq_reprocess-workflow/jobs/test-main-paired/job.json
I could try to debug this between our two systems but that would miss the point -- we would only solve this for our two environments. 

I know a way to build a docker image and add a directory with a .git in it -- you do this a lot for CICD -- but it would require that we build that docker image every time for each checkout of the repository (i.e., each time the workflow is run). This would mean that we would do a docker build command in the run-toil.py. But then I have to add even more special commands to the cwltool solution. This is really not acceptable. And total overkill for what we are trying to do.

You did not say if you like my alternative #1 above. 

Another possibility is that if the CWL workflow gives us a reference to the job arguments, we can just write those into the output we save. I'll see if that's available.

**Comment by tthyer** [comment]
Recording here the conversation that occurred in person this morning. Because the solution to generate the url in a bash script in a cwl step was buggy, we decided to port it to python which we believe will behave more predictably if we control the python dependencies. The pieces of information needed by the provenance step under development are
1. local path to the arguments file `job.json` 
2. github url to that file
3. github url to the amp-rnaseq_reprocess-workflow folder

Following that conversation I ported the bash code to a python utility, `utils/giturl.py`, which can be run independently or imported as a module. `run-toil.py` does the latter to generate the urls above.

**Comment by wpoehlm** [comment]
> 
> 
> Recording here the conversation that occurred in person this morning. Because the solution to generate the url in a bash script in a cwl step was buggy, we decided to port it to python which we believe will behave more predictably if we control the python dependencies. The pieces of information needed by the provenance step under development are
> 
>     1. local path to the arguments file `job.json`
> 
>     2. github url to that file
> 
>     3. github url to the amp-rnaseq_reprocess-workflow folder
> 
> 
> Following that conversation I ported the bash code to a python utility, `utils/giturl.py`, which can be run independently or imported as a module. `run-toil.py` does the latter to generate the urls above.

I'm much happier with this approach.  When I ran the giturl.py script it did have an extra 'https:// ':
https://https://github.com/Sage-Bionetworks/amp-workflows/blob/c7b5b4e71f9e1bfe22f376b6a632e45357feec58/amp-rnaseq_reprocessing/amp-rnaseq_reprocess-workflow/jobs/test-main-paired

However, I am using conda (with all of the necessary packages/versions in the pipfile) instead of a pipenv, so I guess it's possible that this is due to an environment difference.  This is something to consider though as many users will likely not be using pipenv.  Assuming this is not an environment issue, it should be an easy fix to just change:

return f'https://{remote_url}/blob/{sha}{path_from_root}'
to
return f'{remote_url}/blob/{sha}{path_from_root}'

**Comment by tthyer** [comment]
@wpoehlm Thanks for finding that bug. It has nothing to do with the package management. It did have to do with me adding the https outside of the if block where it belonged! So, I generated a requirements.txt and committed that. I'm a little reluctant to remove the Pipfile as it tells the user what the project code actually needs, but since the pip project hasn't finished implementing Pipfiles, it is going to be a while until the broader python community adopts them, so maybe we should just go with the older approach.

**Review by wpoehlm — APPROVED** [review]

**Pull request merged**
