### PR TITLE
Merge Develop Branch Into Master

### PR DESCRIPTION
**Pull request by wpoehlm**
For the past year, we have been using the develop branch as the base for this repo.  Going forward, I think that it makes sense to use a more traditional trunk-based development off master.

### CODE REVIEW

**Review by tthyer — APPROVED** [review]
Hi @wpoehlm, I'm approving this because I generally know what's in it. But I would recommend that in the future, merges to master happen very frequently and over much smaller change increments.

**Comment by wpoehlm** [comment]
> 
> 
> Hi @wpoehlm, I'm approving this because I generally know what's in it. But I would recommend that in the future, merges to master happen very frequently and over much smaller change increments.

Agreed 100%, thanks!

**Review by jaeddy — APPROVED** [review]
I'll echo @tthyer's comments. If things are working and running as expected, I trust that the commits in this PR are solid. 🙂 This has obviously been a ton of work, and the overall improvements are really outstanding. Thanks, @wpoehlm!

**Comment by wpoehlm** [comment]
> 
> 
> I'll echo @tthyer's comments. If things are working and running as expected, I trust that the commits in this PR are solid. 🙂 This has obviously been a ton of work, and the overall improvements are really outstanding. Thanks, @wpoehlm!

Thanks @jaeddy !  When you get a chance, can you set the default branch to master?  I think that would be clearer for users

**Pull request merged**
